const cards = [
    {
        id: 1,
        name: "Tech Conference 2026 with a Very Long Name That Should Be Clamped awndn maw dijojaw mawdkaw awkljd a wa ed awlka scjke  emk sdf esf efj ",
        date: "2026-02-25",
        time: "22:30",
        venue: "Kathmandu",
        entryType: "Free",
        participantsAllowedInTeam: 10,
    },
    {
        id: 2,
        name: "Startup Pitch Night",
        date: "2026-03-10",
        time: "6:30",
        venue: "Pokhara",
        entryType: "Paid",
        entryAmount: 1000,
        participantsAllowedInTeam: 4,
    },
    {
        id: 3,
        name: "Startup Pitch Night",
        date: "2026-03-10",
        time: "13:00",
        venue: "Pokhara",
        entryType: "Paid",
        entryAmount: 200,
        participantsAllowedInTeam: 4,
    },
    {
        id: 4,
        name: "Startup Pitch Night",
        date: "2026-03-10",
        time: "00:00",
        venue: "Pokhara",
        entryType: "Paid",
        entryAmount: 300,
        participantsAllowedInTeam: 1,
    },
    {
        id: 5,
        name: "Tech Confej",
        date: "2026-02-25",
        time: "10:00",
        venue: "Kathmandu",
        entryType: "Free",
        participantsAllowedInTeam: 1,
    },
    {
        id: 6,
        name: "AI Workshop",
        date: "2026-04-05",
        time: "2:00",
        venue: "Online",
        entryType: "Free",
        participantsAllowedInTeam: 2,
    },
    {
        id: 7,
        name: "Web Development Bootcamp",
        date: "2026-04-15",
        time: "9:00",
        venue: "Kathmandu",
        entryType: "Paid",
        entryAmount: 1500,
        participantsAllowedInTeam: 1,
    },
    {
        id: 8,
        name: "Mobile App Development Summit",
        date: "2026-05-01",
        time: "10:00",
        venue: "Pokhara",
        entryType: "Paid",
        entryAmount: 800,
        participantsAllowedInTeam: 3,
    },
    {
        id: 9,
        name: "Cloud Computing Workshop",
        date: "2026-05-20",
        time: "14:00",
        venue: "Online",
        entryType: "Free",
        participantsAllowedInTeam: 5,
    },
    {
        id: 10,
        name: "Cybersecurity Conference",
        date: "2026-06-10",
        time: "9:30",
        venue: "Kathmandu",
        entryType: "Paid",
        entryAmount: 1200,
        participantsAllowedInTeam: 2,
    },
];

export default cards;
